### PR TITLE
Update Versions for Cast, Sift, Remnux -- Added || true to skip failed packages

### PR DESCRIPTION
**Pull request by Jonesckevin**
1. Updated Versions
    - Cast 14.50
    - Sift
    - Remnux
2.  Added = to TERM
3.  Fixed/Changed URL Hyphens for cast
4.  Added Install for Vol3
5.  Updated Readme.
6.  Separated and added `|| True` due to minor errors on installs. - Likely from the update. 

5x Errors on Sift
```
1679.9 time="2024-10-15T07:29:47Z" level=warning msg="first failed state" comment="Failed to install packages: defang==0.5.2. Error: Collecting defang==0.5.2 Downloading defang-0.5.2.tar.gz (4.4 kB) /usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead from cryptography.utils import int_from_bytes /usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead from cryptography.utils import int_from_bytes ERROR: Command errored out with exit status 1: command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '\\'\\'/tmp/pip-install-44_aqeln/defang_48a30095da974c7cbd7a28902f072bb1/setup.py'\\'\\'; __file__='\\'\\'/tmp/pip-install-44_aqeln/defang_48a30095da974c7cbd7a28902f072bb1/setup.py'\\'\\';f=getattr(tokenize, '\\'\\'open'\\'\\', open)(__file__);code=f.read().replace('\\'\\'\\\\r\\\\n'\\'\\', '\\'\\'\\\\n'\\'\\');f.close();exec(compile(code, __file__, '\\'\\'exec'\\'\\'))' egg_info --egg-base /tmp/pip-pip-egg-info-d0qn18wo cwd: /tmp/pip-install-44_aqeln/defang_48a30095da974c7cbd7a28902f072bb1/ Complete output (9 lines): Traceback (most recent call last): File \\<string>\\, line 1, in <module> File \\/usr/local/lib/python3.8/dist-packages/setuptools/__init__.py\\, line 27, in <module> from .dist import Distribution File \\/usr/local/lib/python3.8/dist-packages/setuptools/dist.py\\, line 18, in <module> from . import ( File \\/usr/local/lib/python3.8/dist-packages/setuptools/_entry_points.py\\, line 45, in <module> def validate(eps: metadata.EntryPoints): AttributeError: module 'importlib_metadata' has no attribute 'EntryPoints' ---------------------------------------- WARNING: Discarding https://files.pythonhosted.org/packages/d9/c9/faa3b40c3c3f770d1c1fd98a75bf7b76ef03055809d57dae559835e8aa4c/defang-0.5.2.tar.gz#sha256=a937ebb8313bbbce0466653ed47221cfb5be65d06189d5ab2f99f4e3e305baa4 (from https://pypi.org/simple/defang/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output. ERROR: Could not find a version that satisfies the requirement defang==0.5.2 ERROR: No matching distribution found for defang==0.5.2" component=installer run_num=300 sls=sift.python3-packages.defang

1679.9 time="2024-10-15T07:29:47Z" level=info msg=statistics component=installer failed=5 success=565 total=570
```

### CODE REVIEW

**Comment by digitalsleuth** [comment]
Hi @Jonesckevin , thanks for the review on this. I'm actually looking to create a new docker soon which will support 24.04, as I'm working with SIFT and REMnux authors to update the toolsets. For the time being though, I'll take a look at these and merge after testing.
Cheers!

**Comment by digitalsleuth** [comment]
Hi again @Jonesckevin , so there are a couple of things which will probably be changed in the PR, but the updated versions and the README update look good. Volatility 3 already gets installed with REMnux, so the additional state is no longer required. I'll be adding desktop functionality to the docker (if everything goes well), so there will be some updates added for that. 

And as you've already discovered, REMnux doesn't support 22.04 yet, but both will support 24.04 soon, at which time I'll update the docker container.

Cheers!

**Comment by Jonesckevin** [comment]
Rog. I was putting together my HALp and was updating that section and thought it would be nice to toss that in. Hopefully the update goes well.

Ill be keeping an eye out for the updates. Good Luck

**Comment by digitalsleuth** [comment]
He @Jonesckevin , merged your PR, made some tweaks and pushed them up. Docker is being pushed right now and should be up in the next hour. Cheers, and thanks again!

**Pull request merged**
